
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public DefaultListModel mTrai;
    public DefaultListModel mPhai;
    public main() {
        initComponents();
        mTrai = new DefaultListModel();
        list_sport.setModel(mTrai);
        mTrai.addElement("Bóng đá");       
        mTrai.addElement("Cầu lông");
        mTrai.addElement("Bóng chuyền");
        mTrai.addElement("Bơi");
        mPhai = new DefaultListModel();
        list_love.setModel(mPhai);
        
        //xử lí giao diện
//        int[] indexs1 = list_sport.getSelectedIndices();
//        int[] indexs2 = list_love.getSelectedIndices();
//        if (indexs1.length == ) {
//            btn_oneToRight.setEnabled(false);
//            btn_allToRight.setEnabled(false);
//      }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_love = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_sport = new javax.swing.JList<>();
        btn_oneToRight = new javax.swing.JButton();
        btn_allToRight = new javax.swing.JButton();
        btn_oneToLeft = new javax.swing.JButton();
        btn_allToLeft = new javax.swing.JButton();
        btn_addItem = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(list_love);

        jScrollPane2.setViewportView(list_sport);

        btn_oneToRight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_oneToRight.setText(">");
        btn_oneToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oneToRightActionPerformed(evt);
            }
        });

        btn_allToRight.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_allToRight.setText(">>");
        btn_allToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allToRightActionPerformed(evt);
            }
        });

        btn_oneToLeft.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_oneToLeft.setText("<");
        btn_oneToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oneToLeftActionPerformed(evt);
            }
        });

        btn_allToLeft.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_allToLeft.setText("<<");
        btn_allToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allToLeftActionPerformed(evt);
            }
        });

        btn_addItem.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        btn_addItem.setText("+");
        btn_addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addItemActionPerformed(evt);
            }
        });

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        label1.setText("Danh sách môn yêu thích");

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        label2.setText("Danh sách môn thể thao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_oneToLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_oneToRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_allToRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_allToLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_oneToRight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_allToRight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_oneToLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_allToLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_addItem)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_oneToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oneToRightActionPerformed
        // TODO add your handling code here:
        int[] indexs = list_sport.getSelectedIndices();
        for (int i = indexs.length - 1; i >= 0; i--) {
            mPhai.addElement(mTrai.get(indexs[i]));
            mTrai.remove(indexs[i]);
        }

    }//GEN-LAST:event_btn_oneToRightActionPerformed

    private void btn_allToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allToRightActionPerformed
        // TODO add your handling code here:
        int m = mTrai.getSize();
        for (int i = 0; i < m; i++) {
            mPhai.addElement(mTrai.get(i));
        }
            mTrai.clear();
    }//GEN-LAST:event_btn_allToRightActionPerformed

    private void btn_oneToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oneToLeftActionPerformed
        // TODO add your handling code here:
        int[] indexs = list_love.getSelectedIndices();
        for (int i = indexs.length - 1; i >= 0; i--) {
            mTrai.addElement(mPhai.get(indexs[i]));
            mPhai.remove(indexs[i]);
        }
    }//GEN-LAST:event_btn_oneToLeftActionPerformed

    private void btn_allToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allToLeftActionPerformed
        // TODO add your handling code here:
        int n = mPhai.getSize();
       for(int i = 0; i < n; i++){
           mTrai.addElement(mPhai.get(i));
       }
       mPhai.clear();
    }//GEN-LAST:event_btn_allToLeftActionPerformed

    private void btn_addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addItemActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Nhập tên môn thể thao: ");
        mTrai.addElement(input);       
    }//GEN-LAST:event_btn_addItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addItem;
    public static javax.swing.JButton btn_allToLeft;
    public static javax.swing.JButton btn_allToRight;
    public static javax.swing.JButton btn_oneToLeft;
    public static javax.swing.JButton btn_oneToRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    public static javax.swing.JList<String> list_love;
    public static javax.swing.JList<String> list_sport;
    // End of variables declaration//GEN-END:variables
}
